
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Fallback verhindert, dass `prisma generate` (postinstall) ohne gesetzte
    // DATABASE_URL scheitert — z.B. beim ersten `npm install` vor dem Anlegen der .env.
    url: process.env.DATABASE_URL ?? "file:./prisma/dev.db",
  },
});
